### PR TITLE
Fix #53 - check for different DLLs

### LINKED ISSUE #53: Please include further dlls in Windows installation
Sorry to bother you again, but `nimble` does not work without installing the dlls from the "Other dependencies" package:
https://nim-lang.org/download/dlls.zip

Error message I got:
> could not load: libeay32.dll

I solved this, by downloading the dlls myself and putting them in the .nimble directory.
Would be great, if choosenim could do this for me ;)

### PR DESCRIPTION
**Pull request by genotrance**
Simply check for other DLLs in the tar.gz instead of the files that choosenim comes with.

Worked for me on [Travis](https://travis-ci.org/genotrance/nimble/jobs/588081699#L62).

### CODE REVIEW

**Comment by genotrance** [comment]
PTAL - checking all files.

File: src/choosenim/switcher.nim [hunk 1]
```diff
@@ -61,12 +61,17 @@ proc needsDLLInstall*(params: CliParams): bool =
...
-  let inPath = findExe("libeay32", extensions=["dll"]) != "" and
-               findExe("ssleay32", extensions=["dll"]) != ""
-  let inNimbleBin = fileExists(params.getBinDir() / "libeay32.dll") and
-                    fileExists(params.getBinDir() / "ssleay32.dll")
-  let isInstalled = inPath or inNimbleBin
-  return not isInstalled
+  proc isInstalled(params: CliParams, name: string): bool =
+    let
+      inPath = findExe(name, extensions=["dll"]) != ""
+      inNimbleBin = fileExists(params.getBinDir() / name & ".dll")
```
Comment (dom96) [inline src/choosenim/switcher.nim]: Nit: use ``addFileExt`` instead of appending the extension.
