### PR TITLE
Linux build, windows init.sh fixes

### LINKED ISSUE #216: choosenim does not work on Linux with musl
As in the title, trying to run `curl https://nim-lang.org/choosenim/init.sh -sSf | sh` on a musl based Linux distro results in:

```
choosenim-init: Downloading choosenim-0.6.0_linux_amd64
sh: /tmp/choosenim-0.6.0_linux_amd64: not found
```

This is because choosenim is linked against glibc:

```
thermi:~$ ldd /tmp/choosenim-0.6.0_linux_amd64 
        /lib64/ld-linux-x86-64.so.2 (0x7fc250e12000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fc250e12000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fc250e12000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fc250e12000)
Error relocating /tmp/choosenim-0.6.0_linux_amd64: __fdelt_chk: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: __poll_chk: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: __strdup: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: __memcpy_chk: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: gnu_dev_major: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: __longjmp_chk: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: gnu_dev_minor: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: __fprintf_chk: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: gnu_dev_makedev: symbol not found
Error relocating /tmp/choosenim-0.6.0_linux_amd64: __sprintf_chk: symbol not found
```

### LINKED ISSUE #239: Building 0.7.4 with nimble fails
Attempting to build 0.7.4 with nimble fails without a useful error message:
```
$ nimble install choosenim --verbose
    Reading config file at /home/squattingmonk/.config/nimble/nimble.ini
    Reading official package list
Downloading https://github.com/dom96/choosenim using git
    Cloning latest tagged version: v0.7.4
  Verifying dependencies for choosenim@0.7.4
    Reading official package list
   Checking for nimble@#8f7af86
      Info: Dependency on nimble@#8f7af86 already satisfied
  Verifying dependencies for nimble@#8f7af86
    Reading official package list
   Checking for nimterop@>= 0.6.12
      Info: Dependency on nimterop@>= 0.6.12 already satisfied
  Verifying dependencies for nimterop@0.6.13
    Reading official package list
   Checking for regex@>= 0.15.0
      Info: Dependency on regex@>= 0.15.0 already satisfied
  Verifying dependencies for regex@0.17.0
    Reading official package list
   Checking for unicodedb@>= 0.7.2
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.9.0
    Reading official package list
   Checking for unicodeplus@>= 0.5.0
      Info: Dependency on unicodeplus@>= 0.5.0 already satisfied
  Verifying dependencies for unicodeplus@0.8.0
    Reading official package list
   Checking for unicodedb@>= 0.8
      Info: Dependency on unicodedb@>= 0.8 already satisfied
  Verifying dependencies for unicodedb@0.9.0
    Reading official package list
   Checking for segmentation@>= 0.1
      Info: Dependency on segmentation@>= 0.1 already satisfied
  Verifying dependencies for segmentation@0.1.0
    Reading official package list
   Checking for unicodedb@>= 0.8.0
      Info: Dependency on unicodedb@>= 0.8.0 already satisfied
  Verifying dependencies for unicodedb@0.9.0
    Reading official package list
   Checking for cligen@>= 1.0.0
      Info: Dependency on cligen@>= 1.0.0 already satisfied
  Verifying dependencies for cligen@1.2.2
    Reading official package list
   Checking for nimarchive@>= 0.5.3
      Info: Dependency on nimarchive@>= 0.5.3 already satisfied
  Verifying dependencies for nimarchive@0.5.4
    Reading official package list
   Checking for nimterop@>= 0.6.6
      Info: Dependency on nimterop@>= 0.6.6 already satisfied
  Verifying dependencies for nimterop@0.6.13
    Reading official package list
   Checking for regex@>= 0.15.0
      Info: Dependency on regex@>= 0.15.0 already satisfied
  Verifying dependencies for regex@0.17.0
    Reading official package list
   Checking for unicodedb@>= 0.7.2
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.9.0
    Reading official package list
   Checking for unicodeplus@>= 0.5.0
      Info: Dependency on unicodeplus@>= 0.5.0 already satisfied
  Verifying dependencies for unicodeplus@0.8.0
    Reading official package list
   Checking for unicodedb@>= 0.8
      Info: Dependency on unicodedb@>= 0.8 already satisfied
  Verifying dependencies for unicodedb@0.9.0
    Reading official package list
   Checking for segmentation@>= 0.1
      Info: Dependency on segmentation@>= 0.1 already satisfied
  Verifying dependencies for segmentation@0.1.0
    Reading official package list
   Checking for unicodedb@>= 0.8.0
      Info: Dependency on unicodedb@>= 0.8.0 already satisfied
  Verifying dependencies for unicodedb@0.9.0
    Reading official package list
   Checking for cligen@>= 1.0.0
      Info: Dependency on cligen@>= 1.0.0 already satisfied
  Verifying dependencies for cligen@1.2.2
    Reading official package list
   Checking for analytics@>= 0.2.0
      Info: Dependency on analytics@>= 0.2.0 already satisfied
  Verifying dependencies for analytics@0.2.0
    Reading official package list
   Checking for uuids@>= 0.1.7
      Info: Dependency on uuids@>= 0.1.7 already satisfied
  Verifying dependencies for uuids@0.1.10
    Reading official package list
   Checking for isaac@>= 0.1.3
      Info: Dependency on isaac@>= 0.1.3 already satisfied
  Verifying dependencies for isaac@0.1.3
    Reading official package list
   Checking for osinfo@>= 0.3.0
      Info: Dependency on osinfo@>= 0.3.0 already satisfied
  Verifying dependencies for osinfo@0.3.2
    Reading official package list
   Checking for osinfo@>= 0.3.0
      Info: Dependency on osinfo@>= 0.3.0 already satisfied
  Verifying dependencies for osinfo@0.3.2
 Installing choosenim@0.7.4
   Building choosenim/choosenim using c backend
    Prompt: Build failed for 'choosenim@0.7.4', would you like to try installing 'choosenim@#head' (latest unstable)? [y/N]
    Answer: n
     Error: Aborting installation due to build failure
```
## Details
OS: Arch Linux 5.9.1
Nim: 1.4.0
Nimble: 0.11.0

### PR DESCRIPTION
**Pull request by genotrance**
- Switch init.sh to download standalone binary on windows
- musl static building only in CI
- Fixes #239 - not building on Linux w/o musl
- Fixes #216 - musl support for proxyexe

### CODE REVIEW

**Comment by genotrance** [comment]
@dom96 - PTAL

cc @alaviss

**Comment by genotrance** [comment]
Still some issues, hold off on merge.

**Comment by genotrance** [comment]
This is ready to go - please review and merge.

**Review by dom96 — CHANGES_REQUESTED** [review]
Why did you move the static build flags out of the .nims? I thought we agreed to have a flag that could be passed to ``nim`` for a static build, and just specify these flags in that config file behind a `-d:static` or something?

Since this is nimscript I think you could easily reuse that config for proxyexe and you wouldn't need this new `-d:skipBuild` flag which I'm also not a big fan of.

**Comment by genotrance** [comment]
All such flags can be specified on the command line with - -passL, either with Nim or nimble. Why an extra flag?

-d:skipBuild was added to avoid building with the wrong flags or local testing. 

If you have better ideas for this, please suggest specifics. This took several hours of time to get right, it's not a two minute change. I also tested this with my travister matrix which tests normal builds that users would do locally.

https://travis-ci.org/github/genotrance/travister/builds/738344603

**Comment by dom96** [comment]
> All such flags can be specified on the command line with - -passL, either with Nim or nimble. Why an extra flag?

Because if I then want to locally create a static build then I need to copy and paste the flags manually from the CI scripts...

> If you have better ideas for this, please suggest specifics. This took several hours of time to get right, it's not a two minute change. I also tested this with my travister matrix which tests normal builds that users would do locally.

* Create a `proxyexe.nims` file in `choosenimpkg`:

```nim
when defined(staticBuild):
  putEnv("CC", "musl-gcc")
  switch("gcc.exe", "musl-gcc")
  switch("gcc.linkerexe", "musl-gcc")
  when not defined(OSX):
    switch("passL", "-static")
```

* In ``choosenim.nims``: ``import "choosenimpkg/proxyexe.nims"`` (I'm not sure if this works, but AFAIK that is the point of .nims, so it would be pretty ridiculous if there wasn't a way to do it, maybe you need to wrap that stuff in a proc and call it from both the ``proxyexe.nims`` and the ``choosenim.nims``)

* In CI just pass the `-d:staticBuild` flag
* In switcher.nim:

```nim
when defined(staticBuild):
  cmd.add("-d:staticBuild")
```

(As an aside, I'm not sure where the new flags you've added for Linux/Windows belong (-lpthread/-lws2_32). If they're also related to staticBuild then they should go under that ``when`` otherwise they can stay in the .nims. Please do explain what they're for though.)

**Comment by genotrance** [comment]
@dom96 - PTAL - ready to go.

Also, please migrate from travis-ci.org to travis-ci.com so that build times improve. Should take 5 minutes to migrate your repos over.

File: src/choosenimpkg/switcher.nim [hunk 1]
```diff
@@ -11,7 +11,9 @@ when defined(windows):
 proc compileProxyexe() =
   var cmd = "nim c"
   when defined(release):
-    cmd.add " -d:release"
+    cmd.add " -d:danger"
```
Comment (dom96) [inline src/choosenimpkg/switcher.nim:14]: Please don't do that. Release is fine...

**Review by dom96 — APPROVED** [review]
Much better, thank you! Please resolve my comment before merging.

File: src/choosenimpkg/switcher.nim (hunk 1 above)
Comment (genotrance) [reply src/choosenimpkg/switcher.nim:14]: I made it danger cause the shims get called hundreds of times and are simple code. Seemed worth it to me to optimize them a bit more.

Comment (dom96) [reply src/choosenimpkg/switcher.nim:14]: I doubt it'll have a significant impact on the performance, but it may have a big impact on our ability to understand what's breaking.
