### PR TITLE
Use GITHUB_TOKEN env var if present

### LINKED ISSUE #208: Github API rate limited exceeded
I use choosenim in several Github Actions and am consistently exceeding the Github API Rate limits.  I'll admit that this seems to me like a Github problem, not a choosenim problem, but I don't know how to convince Github to fix it.

It manifests as this error:

```
Error: unhandled exception: download.nim(342, 14) `responseCode == 200` Expected HTTP code 200 got 403 for https://api.github.com/repos/nim-lang/nightlies/releases [AssertionError]
```

I've verified that the rate limits are the problem with:

```
curl https://api.github.com/rate_limit
  shell: /bin/bash -e {0}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 0,
      "reset": 1595258445
    },
    "graphql": {
      "limit": 0,
      "remaining": 0,
      "reset": 1595258786
    },
    "integration_manifest": {
      "limit": 5000,
      "remaining": 5000,
      "reset": 1595258786
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1595255246
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 0,
    "reset": 1595258445
  }
}
```

If choosenim allowed me to provide Github API credentials to be used in Github API requests, I could make those requests under my own account (rather than the anonymous rate).  I'll see if I can make a PR, but maybe someone else could make it much quicker.

### PR DESCRIPTION
**Pull request by iffy**
This change inserts the value of the env var `GITHUB_TOKEN` into the authentication section of Github API URLs.

This is to fix #208 

- I don't know how to build `choosenim` to test this, so I don't know if it works
- I don't know if curl as used by choosenim will accept a URL of this format
- What documentation changes are needed?  Would you rather it be a command line param?

I'm fine if you want to throw this away and do your own implementation.

### CODE REVIEW

**Comment by genotrance** [comment]
Best way to test this is to update the tester which works around the API limit today.

https://github.com/dom96/choosenim/blob/master/tests/tester.nim#L199

We can add a read-only token to the choosenim CI and see if the build passes.

The env var is the best way for tokens with a CI. However, a file is more appropriate for regular users. See the nimble implementation to see how it deals with this. Might be best to keep choosenim and nimble similar.

https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/publish.nim#L52

File: src/choosenimpkg/download.nim [hunk 1]
```diff
@@ -55,6 +55,13 @@ proc showBar(fraction: float, speed: BiggestInt) =
                 ])
   stdout.flushFile()
 
+proc addGithubAuthentication(url:string):string =
+  let ghtoken = getEnv("GITHUB_TOKEN")
+  if ghtoken == "":
+    return url
+  else:
+    return url.replace("https://api.github.com", "https://" & ghtoken & "@api.guthub.com")
```
Comment (dom96) [inline src/choosenimpkg/download.nim:63]: > api.guthub.com

Hopefully you're not trying to steal people's tokens and this is just a simple type :P

**Comment by dom96** [comment]
> I don't know how to build choosenim to test this, so I don't know if it works

``nimble build`` should work...

File: src/choosenimpkg/download.nim (hunk 1 above)
Comment (iffy) [reply src/choosenimpkg/download.nim:63]: Oops... it's a typo, but I checked and it is registered to someone: https://domainr.com/guthub.com?q=guthub.com

**Comment by iffy** [comment]
`nimble build` worked great!

> What's the authoritative spec for GITHUB_TOKEN? What does it contain? username:password?
It's an opaque hexadecimal string that can be used as a username in an HTTP request.  You can also use it as a Bearer token in an HTTP header. I've added some cli documentation that might make it clearer?

> Also, please add some code to show an info message when the token is used.
Done

**Comment by iffy** [comment]
I'm not sure why this change causes this build failure:

```
/Users/travis/build/dom96/choosenim/tests/tester.nim(179, 19): Check failed: exitCode == QuitSuccess
exitCode was 1
QuitSuccess was 0
   Updating devel
    Warning fatal: unable to access 'https://github.com/nim-lang/Nim/': Could not resolve host: github.com
        ... git ls-remote failed
Downloading Nim devel from GitHub
/Users/travis/build/dom96/choosenim/src/choosenim.nim(299) choosenim
/Users/travis/build/dom96/choosenim/src/choosenim.nim(274) performAction
/Users/travis/build/dom96/choosenim/src/choosenim.nim(166) update
/Users/travis/build/dom96/choosenim/src/choosenim.nim(24) installVersion
/Users/travis/build/dom96/choosenim/src/choosenimpkg/download.nim(282) download
/Users/travis/build/dom96/choosenim/src/choosenimpkg/download.nim(253) downloadImpl
/Users/travis/build/dom96/choosenim/src/choosenimpkg/download.nim(188) downloadFile
/Users/travis/build/dom96/choosenim/src/choosenimpkg/download.nim(152) downloadFileCurl
/Users/travis/build/dom96/choosenim/src/choosenimpkg/download.nim(70) checkCurl
Error: unhandled exception: CURL failed: Couldn't resolve host name [AssertionError]
/Users/travis/build/dom96/choosenim/tests/tester.nim(188, 19): Check failed: exitCode == QuitSuccess
exitCode was 1
QuitSuccess was 0
/Users/travis/build/dom96/choosenim/tests/tester.nim(193, 17): Check failed: inLines(output.processOutput, "latest changes")
/Users/travis/build/dom96/choosenim/tests/tester.nim(194, 17): Check failed: inLines(output.processOutput, "building")
[FAILED] can update devel with git
```

**Comment by genotrance** [comment]
Restarting the failed job - travis network is flaky sometimes.

File: src/choosenimpkg/download.nim [hunk 2]
```diff
@@ -55,6 +55,15 @@ proc showBar(fraction: float, speed: BiggestInt) =
                 ])
   stdout.flushFile()
 
+proc addGithubAuthentication(url:string):string =
```
Comment (dom96) [inline src/choosenimpkg/download.nim:58]: Nit:
```suggestion
proc addGithubAuthentication(url: string): string =
```
